name: Buildroot builder

on:
  schedule:
    - cron: '24 8 * * *'
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install --no-install-recommends sed make binutils build-essential diffutils gcc g++ bash patch gzip bzip2 perl tar cpio unzip rsync file bc findutils wget

      - name: Fetch Buildroot
        run: |
          git clone https://github.com/buildroot/buildroot.git /opt/buildroot
          cd /opt/buildroot
          make raspberrypi4_64_defconfig
          make all